name = "AustralianElectricityMarket"
uuid = "1bf50fc4-d6fd-47c1-85ec-4976c2b5cc58"
authors = ["Youssef Miftah <miftahyo@outlook.fr> and contributors"]
version = "1.0.0-DEV"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
TidierDB = "86993f9b-bbba-4084-97c5-ee15961ad48b"

[compat]
Chain = "0.6.0"
CondaPkg = "0.2.29"
DataFrames = "1.7.0"
Dates = "1.11.0"
PowerSystems = "4.6.2"
PythonCall = "0.9.26"
TidierDB = "0.8.7"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Aqua", "Test", "TestItems"]
