[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
AustralianElectricityMarkets = "1bf50fc4-d6fd-47c1-85ec-4976c2b5cc58"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
QuackIO = "7b8617ff-c43a-4c37-a28b-ad5a1791f8ae"
TidierDB = "86993f9b-bbba-4084-97c5-ee15961ad48b"

[sources]
AustralianElectricityMarkets = {path = "/home/simba/.julia/dev/AustralianElectricityMarkets"}
